# Please read this -> https://github.com/Stefanuk12/luarmor-deploy-action/tree/main

name: Deploy Script to Luarmor

on:
  workflow_dispatch:

jobs:
  bundle:
    name: Bundle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Pesde
        uses: lumin-org/setup-pesde@v0.3.1
        with:
          cache: true

      - name: Install dependencies
        run: |
          pesde install
          pesde run config

      - name: Darklua
        run: |
          ~/.pesde/bin/darklua -V
          darklua=$(find ~/.pesde/bin/.tool_storage -type f -name 'darklua*' -printf '%T@ %p\n' | sort -nr | head -n1 | cut -d' ' -f2-)
          "$darklua" process src/init.luau dist.lua -c .meta/.darklua.json

      - name: Upload dist.lua artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist.lua

  deploy:
    runs-on: [self-hosted]
    needs:
      - bundle

    steps:
      - name: Download dist.lua artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./

      - name: Deploy to Luarmor
        uses: stefanuk12/luarmor-deploy-action@v1.0.0
        with:
          api-key: ${{ secrets.LUARMOR_API_KEY }}
          script-id: "your-script-id"
          file: "dist.lua"
